# ~/.config/foot/foot.ini

# Fuentes que se Usaran
font=JetBrainsMono Nerd Font:size=10
font-bold=JetBrainsMono Nerd Font:size=10:style=Bold
font-italic=JetBrainsMono Nerd Font:size=10:style=Italic

# Ajustes de la ventana
pad=5x5

[mouse]
hide-when-typing=yes

[cursor]
# Estilo de cursor en barra y parpadeante
style=beam
blink=yes

[colors-dark]
# Transparencia intermedia
alpha=0.85

# Colores del Fondo
background=121212            # Negro oscuro clásico de terminal
foreground=e0e0e0            # Blanco estándar limpio

# Paleta Normal
regular0=000000              # Negro
regular1=cd3131              # Rojo estándar
regular2=0dbc79              # Verde estándar
regular3=e5e510              # Amarillo estándar
regular4=0095b6              # Azul con un toque Cyan (Azul océano)
regular5=bc3fbc              # Magenta estándar
regular6=00a8a8              # Cyan (Un turquesa clásico, pero más oscuro y maduro)
regular7=e5e5e5              # Blanco

# Paleta Brillante
bright0=666666               # Gris oscuro
bright1=f14c4c               # Rojo brillante
bright2=23d18b               # Verde brillante
bright3=f5f543               # Amarillo brillante
bright4=38b0de               # Azul brillante tirando a cyan (Azul cielo)
bright5=d670d6               # Magenta brillante
bright6=29b6f6               # Cyan brillante (Suave, el "toque" justo sin ser neón)
bright7=ffffff               # Blanco brillante
